[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "lab"
readme  = "README.md"

# TODO: Change your package specifications
# -----------------------------------------------------------------
title = "Extension Template"
author = "Zhengyu Zhang + Isaac Lab/Orbit Project Developers"
maintainer = "Zhengyu Zhang"
maintainer_email = "zzyoctopus@gmail.com"
description="Extension Template for Tycho + Issac lab"
repository = "git@github.com:zoctipus/IsaacLab_Tycho.git"
keywords = ["extension", "template", "lab"]
# -----------------------------------------------------------------

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
# TODO: Change your package name
# -----------------------------------------------------------------
name = "lab.tycho"
# -----------------------------------------------------------------

[lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"